version: '3.9'
services:
  app:
    restart: always
    build:
      context: .
    volumes:
      - .:/app
    command: rails s -b 0.0.0.0 -p 3000
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    restart: always
    image: mysql:8.0
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    tty: true
    command: mysqld --character-set-server=utf8mb4 --explicit_defaults_for_timestamp=true --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
